### ISSUE TITLE
Bug when copying entities to new file

### ISSUE THREAD

**Issue by thaiguer** [DomCR/ACadSharp#445]
Hello,
I'm getting the following exception:
System.ArgumentException: 'An item with the same key has already been added. Key: 2890'

The complete message:
System.ArgumentException
  HResult=0x80070057
  Message=An item with the same key has already been added. Key: 2890
  Source=System.Private.CoreLib
  StackTrace:
   at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException[T](T key)
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at ACadSharp.IO.DWG.DwgObjectWriter.writeReactorsAndDictionaryHandle(CadObject cadObject)
   at ACadSharp.IO.DWG.DwgObjectWriter.writeEntityMode(Entity entity)
   at ACadSharp.IO.DWG.DwgObjectWriter.writeCommonEntityData(Entity entity)
   at ACadSharp.IO.DWG.DwgObjectWriter.writeSolid(Solid solid)
   at ACadSharp.IO.DWG.DwgObjectWriter.writeEntity(Entity entity)
   at ACadSharp.IO.DWG.DwgObjectWriter.writeBlockEntities()
   at ACadSharp.IO.DWG.DwgObjectWriter.Write()
   at ACadSharp.IO.DwgWriter.writeObjects()
   at ACadSharp.IO.DwgWriter.Write()
   at Program.<Main>$(String[] args) in C:\dev\MySolution\MyProject.Console\Program.cs:line 22

Here is my code:
```
using ACadSharp;
using ACadSharp.IO;

Console.WriteLine("Hello, World!");

string sourceFile = @"C:\dev\tablet.dwg";
string targetFile = @"C:\dev\just a drawing222.dwg";

using (DwgReader reader = new DwgReader(sourceFile))
{
    CadDocument doc = reader.Read();
    CadDocument newDoc = new CadDocument();

    foreach (var entity in doc.Entities)
    {
        doc.Entities.Remove(entity);
        newDoc.Entities.Add(entity);
    }

    using (DwgWriter writer = new DwgWriter(targetFile, newDoc))
    {
        writer.Write();
    }
}
```

Im using ACadSharp 1.0.0, but in the ACadSharp 2.4.0-beta the same thing happend.
[tablet.zip](https://github.com/user-attachments/files/16944242/tablet.zip)

I got this error with a file from work, but I can reproduce it with the file above, that I got from [AutoCAD Sample Files](https://www.autodesk.com/support/technical/article/caas/tsarticles/ts/6XGQklp3ZcBFqljLPjrnQ9.html).

Saving the file with "DxfWriter" almost works. It executes, but the output file is not great. There are texts wich are deslocated and hatches doesn't seem to be there.

**Comment by DomCR** [comment]
Hi @thaiguer,

I've found an issue when writing the entity type `Solid`, I'll open a branch to solve the issue.

As for the missing entities when rewriting the file, I'll open an exploration branch to see what's going on.

Thanks for the report!
